### ISSUE TITLE
Getting 'exit code: 1' with 'manage start'

### ISSUE THREAD

**Issue by rahimrasool** [uchicago-dsi/textbook-datascience-1#52]
Getting the following error with manage start. This is happening on just one machine, works fine on others. Any idea of what could cause it?

```
Error response from daemon: Head “https://ghcr.io/v2/chicago-cdac/textbook-jupyter-service/manifests/latest”: denied
[ProcessExecutionError] Unexpected exit code: 1
Command line: | /usr/local/bin/docker pull [ghcr.io/chicago-cdac/textbook-jupyter-service:latest](http://ghcr.io/chicago-cdac/textbook-jupyter-service:latest)
```

**Comment by jesteria** [comment]
Not sure what to say about this one from the excerpt above, except that it appears to be pulling from the old organization name, `chicago-cdac`. Previously that would redirect to the new URL, (but perhaps not anymore). Regardless, updating the GitHub repository checkout would fix that.

Was this perhaps closed because it's not a problem anymore?

**Comment by rahimrasool** [comment]
Yes, the person who reported this problem cloned the repo again and this error didn't appear anymore. Thanks for clarifying.
